language: 
        node_js

before install:
        
before_script:
        - npm install -g gulp-cli
        - psql -c 'create database bsz;' -U postgres
script:

services:
        -postgresql
cache:
        npm
