language: 
        node_js

before install:
        
before_script:
        - psql -c 'create database bsz;' -U postgres
        - psql -d bsz -U postgres -a -f ./db/database.sql
script:

services:

cache:
        npm
